### ISSUE TITLE
chatglm-6B A100，80G显卡，在单机多卡并行时报OOM，把lora改成8了也OOM，改成torchrun也OOM

### ISSUE THREAD

**Issue by hangzeli08** [PhoebusSi/Alpaca-CoT#103]

**Comment by PhoebusSi** [comment]
群里有人遇到过这个问题 改了下bitsandbytes的版本就可以运行了。试试bitsandbytes==0.37.2

**Comment by hangzeli08** [comment]
还是不行，遇到数据量稍大点的就不行了，请教还有别的办法吗～

**Comment by PhoebusSi** [comment]
试试 --lora_r 16 --lora_alpha 16

**Comment by hangzeli08** [comment]
已经 --lora_r 8 --lora_alpha 8， 坚持1个多小时后会oom，正常应该需要多大的显存啊，我这种情况正常吗，其他人还有怎么解决的吗，或者有其他解决方案吗，还是我哪个包需要安装别的版本。

**Comment by hangzeli08** [comment]
这个和数据集，数据量有关系吗，感觉不同的数据竟然占用的显存大小不同，你们正常用的时候实际占的的显存是多大啊～

**Comment by dkqkxx** [comment]
> 这个和数据集，数据量有关系吗，感觉不同的数据竟然占用的显存大小不同，你们正常用的时候实际占的的显存是多大啊～

如果数据集每一条都比较长的话，可能出现这种情况，
请修改 uniform_finetune.py 
```
if "chatglm" in args.model_type:
        def prompt_tokenize(prompt):
            input_ids = tokenizer.encode(prompt,
                                         truncation=True,
                                         max_length=args.cutoff_len,
                                         #    padding="max_length",
                                         padding=False,
                                         )
            return {
                "input_ids": input_ids,
                "labels": copy.deepcopy(input_ids)
            }
        def completion_tokenize(completion):
            input_ids = tokenizer.encode(completion) #, add_special_tokens=False)
            return {
                "input_ids": input_ids,
                "labels": copy.deepcopy(input_ids)
            }
     ```
      input_ids = tokenizer.encode(completion) #, add_special_tokens=False) 这里设置 max_length=args.cutoff_len，然后试试单卡版本是否还有这种问题

**Comment by hangzeli08** [comment]
目前 我发现了一个 非常让我感到匪夷所思的现象，就是数据不变的情况下，都是COT那个， 我的A100 80G显存，占用了79G，1个小时后报oom，我的V100，32G显存，竟然只占用了12G? 这？它在V100和A100下表现不同吗？动态变化吗难道？

**Comment by shibing624** [comment]
> > 这个和数据集，数据量有关系吗，感觉不同的数据竟然占用的显存大小不同，你们正常用的时候实际占的的显存是多大啊～
> 
> 如果数据集每一条都比较长的话，可能出现这种情况， 请修改 uniform_finetune.py
> 
> ```
> if "chatglm" in args.model_type:
>         def prompt_tokenize(prompt):
>             input_ids = tokenizer.encode(prompt,
>                                          truncation=True,
>                                          max_length=args.cutoff_len,
>                                          #    padding="max_length",
>                                          padding=False,
>                                          )
>             return {
>                 "input_ids": input_ids,
>                 "labels": copy.deepcopy(input_ids)
>             }
>         def completion_tokenize(completion):
>             input_ids = tokenizer.encode(completion) #, add_special_tokens=False)
>             return {
>                 "input_ids": input_ids,
>                 "labels": copy.deepcopy(input_ids)
>             }
> ```
> 
> ```
>   input_ids = tokenizer.encode(completion) #, add_special_tokens=False) 这里设置 max_length=args.cutoff_len，然后试试单卡版本是否还有这种问题
> ```

这个encode的max_length 要合入到代码里面更合适吧`max_length=args.cutoff_len`

**Comment by dkqkxx** [comment]
> > > 这个和数据集，数据量有关系吗，感觉不同的数据竟然占用的显存大小不同，你们正常用的时候实际占的的显存是多大啊～
> > 
> > 
> > 如果数据集每一条都比较长的话，可能出现这种情况， 请修改 uniform_finetune.py
> > ```
> > if "chatglm" in args.model_type:
> >         def prompt_tokenize(prompt):
> >             input_ids = tokenizer.encode(prompt,
> >                                          truncation=True,
> >                                          max_length=args.cutoff_len,
> >                                          #    padding="max_length",
> >                                          padding=False,
> >                                          )
> >             return {
> >                 "input_ids": input_ids,
> >                 "labels": copy.deepcopy(input_ids)
> >             }
> >         def completion_tokenize(completion):
> >             input_ids = tokenizer.encode(completion) #, add_special_tokens=False)
> >             return {
> >                 "input_ids": input_ids,
> >                 "labels": copy.deepcopy(input_ids)
> >             }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >   input_ids = tokenizer.encode(completion) #, add_special_tokens=False) 这里设置 max_length=args.cutoff_len，然后试试单卡版本是否还有这种问题
> > ```
> 
> 这个encode的max_length 要合入到代码里面更合适吧`max_length=args.cutoff_len`
> 
> 再提一个pr： uniform_finetune.py 166行，加个lora_target_modules的转化为list的逻辑： args.lora_target_modules = ['query_key_value'] if args.lora_target_modules == 'query_key_value' else args.lora_target_modules

感谢，已修改
