### ISSUE TITLE
使用MOSS报错：RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by orangefish08** [PhoebusSi/Alpaca-CoT#106]
请问大家有遇到过这个报错吗？

环境：
python3.8
transformers使用git上最新
bitsandbytes==0.37.2
torch==1.13.1

![649a478528307ab8390b538e7b4a942](https://user-images.githubusercontent.com/34035598/236656085-8a628bf9-0c00-44eb-a40a-00ae67624539.jpg)

**Comment by dkqkxx** [comment]
看起来是cuda版本的问题，能提供你的gpu型号，cuda版本等系统信息吗

**Comment by orangefish08** [comment]
用的是V100 16g显存
cuda版本是11.1

**Comment by dkqkxx** [comment]
> 用的是V100 16g显存 cuda版本是11.1

代码执行中显存占用如何？

**Comment by orangefish08** [comment]
> 

用了两张卡跑的，CUDA_VISIBLE_DEVICES=0,1 python3 uniform_finetune.py ...
![766e90efd41188d08769d8bc5921494](https://user-images.githubusercontent.com/34035598/236725952-710276c2-6994-4e8c-9100-23f624c3e939.jpg)

我尝试跑了llama是没问题的

**Comment by dkqkxx** [comment]
可以分别尝试以下方案：
1. 升级cuda, bitsandbytes,transformers版本
2.  ``
    model_class.model.from_pretrained(args.model_name_or_path,
                                                load_in_8bit=True,
                                                device_map=device_map) 
    `` 
    load_in_8bit=True 修改为 torch_dtype=torch.float16 
3. 参考 https://github.com/huggingface/transformers/pull/22888

**Comment by SiriusWy** [comment]
model.half()试试？

**Comment by orangefish08** [comment]
已解决，谢谢回复。

model_class.model.from_pretrained(args.model_name_or_path, load_in_8bit=True, device_map=device_map) 
load_in_8bit=True 修改为 torch_dtype=torch.float16
