### ISSUE TITLE
alpaca-belle-cot是指哪个数据？

### ISSUE THREAD

**Issue by shibing624** [PhoebusSi/Alpaca-CoT#110]
alpaca-belle-cot 数据在代码中指定的是`alpaca-belle-cot": "./data/alcapa_plus_belle_plus_cot.json`, hf dataset 里面具体是指哪个文件呢？

https://huggingface.co/datasets/QingyiSi/Alpaca-CoT/tree/main/Chinese-instruction-collection 里面的[CoT_Chinese_data.json](https://huggingface.co/datasets/QingyiSi/Alpaca-CoT/blob/main/Chinese-instruction-collection/CoT_Chinese_data.json) 文件，还加上0.5M的belle 中文数据吗？

**Comment by dkqkxx** [comment]
> alpaca-belle-cot 数据在代码中指定的是`alpaca-belle-cot": "./data/alcapa_plus_belle_plus_cot.json`, hf dataset 里面具体是指哪个文件呢？
> 
> https://huggingface.co/datasets/QingyiSi/Alpaca-CoT/tree/main/Chinese-instruction-collection 里面的[CoT_Chinese_data.json](https://huggingface.co/datasets/QingyiSi/Alpaca-CoT/blob/main/Chinese-instruction-collection/CoT_Chinese_data.json) 文件，还加上0.5M的belle 中文数据吗？

您可以自行制定想用的数据集，如 --data ../belle_cn/belle_instructions/belle_data1M_cn.json
至于alpaca-belle-cot 在 [Alpaca-CoT](https://huggingface.co/datasets/QingyiSi/Alpaca-CoT/tree/main)
/
[combination](https://huggingface.co/datasets/QingyiSi/Alpaca-CoT/tree/main/combination)
/
alpaca_plus_belle_data.json
