### ISSUE TITLE
为什么我训练的lora的adapter_model.bin最后只有443字节

### ISSUE THREAD

**Issue by SiriusWy** [PhoebusSi/Alpaca-CoT#111]
python3.9,其它库都是按照requirement.txt中安装的

**Comment by dkqkxx** [comment]
peft 问题， 可以使用checkpoint中的模型

**Comment by SiriusWy** [comment]
> peft 问题， 可以使用checkpoint中的模型

谢谢回复哈
https://github.com/huggingface/peft/issues/286
注释掉这块也行

> peft 问题， 可以使用checkpoint中的模型
