### ISSUE TITLE
作inference的时候，下载失败

### ISSUE THREAD

**Issue by JetHong** [PhoebusSi/Alpaca-CoT#12]
![image](https://user-images.githubusercontent.com/20529249/228469366-6a8cb8d8-41cd-4e54-8263-70725d1f3c92.png)

**Comment by PhoebusSi** [comment]
如果自动下载失败，可以手动从这里下载https://huggingface.co/decapoda-research/llama-7b-hf/tree/main，然后把所有的文件放到同一个本地路径下，并将该路径设置给`BASE_MODEL`即可。

**Comment by JetHong** [comment]
已解决，thansk～
