### ISSUE TITLE
GPTeacher Code-Instruct

### ISSUE THREAD

**Issue by teknium1** [PhoebusSi/Alpaca-CoT#122]
I uploaded a 5350~ entry code-instruct by gpt4 dataset to GPTeacher, in case someone wants to include it here, it looks like just toolformer, general, and roleplay is added

The newly added dataset is here: https://github.com/teknium1/GPTeacher/tree/main/Codegen

**Comment by dkqkxx** [comment]
> 我上传了一个 5350~ entry code-instruct by gpt4 dataset 到 GPTeacher，以防有人想在这里包含它，它看起来只是添加了 toolformer，general 和 roleplay
> 
> 新添加的数据集在这里：[https ://github.com/teknium1/GPTeacher/tree/main/Codegen](https://github.com/teknium1/GPTeacher/tree/main/Codegen)

thanks
