### ISSUE TITLE
8卡V100跑moss OOV

### ISSUE THREAD

**Issue by uloveqian2021** [PhoebusSi/Alpaca-CoT#124]
大佬能给一个能跑的起来的参数设置吗

**Comment by dkqkxx** [comment]
python3 uniform_finetune.py   ---model_type moss --model_name_or_path fnlp/moss-moon-003-sft  \
    --data alpaca --lora_target_modules q_proj v_proj --per_gpu_train_batch_size 1 \
    --learning_rate 3e-4 --epochs 3
在3x3090(24g)  即可运行

**Comment by uloveqian2021** [comment]
> python3 uniform_finetune.py ---model_type moss --model_name_or_path fnlp/moss-moon-003-sft --data alpaca --lora_target_modules q_proj v_proj --per_gpu_train_batch_size 1 --learning_rate 3e-4 --epochs 3 在3x3090(24g) 即可运行

好的，我试试
