### ISSUE TITLE
Prompt设置

### ISSUE THREAD

**Issue by Ricardokevins** [PhoebusSi/Alpaca-CoT#130]
ChatGLM，MOSS似乎采用的Prompt格式都不同，但是在训练代码里似乎没有进行设置？而是简单的都使用了Alpaca的prompt格式。
这个是否会影响最终的性能结果？

**Comment by PhoebusSi** [comment]
建议为垂域任务探索各自适合的prompt。不过在通用的对话能力上各家prompt造成性能差异不大，主要影响因素还是数据本身。
