### ISSUE TITLE
More data

### ISSUE THREAD

**Issue by KnutJaegersberg** [PhoebusSi/Alpaca-CoT#15]
Swype will properly release their instruction fine tuning dataset real soon: 
https://huggingface.co/datasets/swype/instruct-102.4k

And there is also: 
https://github.com/nomic-ai/gpt4all

**Comment by KnutJaegersberg** [comment]
I forgot this one, damn 
https://github.com/mobarski/alpaca-libre

**Comment by PhoebusSi** [comment]
Thank you for the reminder.  We will collect and format these as soon as possible.
