### ISSUE TITLE
main分支下的readme顺序，以及base模型能否提供huggingface的链接

### ISSUE THREAD

**Issue by nuocheng** [PhoebusSi/Alpaca-CoT#183]
【1】我注意到main分支下readme里1.先是进行微调，2.再进行Inference，3.再进行Parameter merging。不应该是1,3,2的顺序吗？因为2.中得到的仅仅只是lora的权重参数，而不是全部的参数，能否在部分权重之下就能进行Inference呢？

【2】另外一个我在进行第一步Finetuning的过程发现，我之前使用的llama-13b的模型跑不起来，你能提供一个能正常运行的base模型吗

【3】分支tabular_llm下的代码的运行方式似乎与分支main下的不一样。

**Comment by nuocheng** [comment]
`CUDA_VISIBLE_DEVICES=1 python3 uniform_finetune.py --model_type chatglm --model_name_or_path huggingface.co/THUDM/chatglm3-6b --data ./data/formatted_cot_data/aqua_train.json ./data/formatted_cot_data/ecqa_train.json ./data/formatted_cot_data/esnli_train.json --lora_target_modules query_key_value --lora_r 32 --lora_alpha 32 --lora_dropout 0.1`
运行uniform_finetune.py这个脚本进行进行微调，出现了
![image](https://github.com/PhoebusSi/Alpaca-CoT/assets/31612743/92227b12-622b-475a-be3f-c0b2b50d5b74)
这个问题。
使用的数据是库中自带的几个jsno数据

**Comment by PhoebusSi** [comment]
【1】 其实3是可有可无的一步，在1微调得到lora权重后，2inference时同时加载llm和lora的权重即可完成推理。而3则是将lora合进llm的操作，用lora替代原有llm中的矩阵，得到一个新的llm，可直接用新llm完成推理，不再需要同时再加载llm和lora权重了。因此3并不是一个必要操作，基本上1和2就满足了训练和测试的需求。

【2】用uniform_finetune.py跑llama-13应该是能跑起来的，是不是本地显存过低？

【3】tabular_LLM主要是提供了相关tabular数据，模型训练相关的代码请参考main分支。

**Comment by PhoebusSi** [comment]
> `CUDA_VISIBLE_DEVICES=1 python3 uniform_finetune.py --model_type chatglm --model_name_or_path huggingface.co/THUDM/chatglm3-6b --data ./data/formatted_cot_data/aqua_train.json ./data/formatted_cot_data/ecqa_train.json ./data/formatted_cot_data/esnli_train.json --lora_target_modules query_key_value --lora_r 32 --lora_alpha 32 --lora_dropout 0.1` 运行uniform_finetune.py这个脚本进行进行微调，出现了 ![image](https://private-user-images.githubusercontent.com/31612743/291768541-92227b12-622b-475a-be3f-c0b2b50d5b74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTc1MjMsIm5iZiI6MTcwMzA1NzIyMywicGF0aCI6Ii8zMTYxMjc0My8yOTE3Njg1NDEtOTIyMjdiMTItNjIyYi00NzVhLWJlM2YtYzBiMmI1MGQ1Yjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA3MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNmMwMjE5NzQ3ZTg1OTE5NGJlMzI5NDE2YjFmODE3Y2U2OTEzMDZlOThlZjc5ZGNiZTc4YTg4OWU2YzA1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MaQwpz_lgWNYza4Zn9RiNr1Eiaisa86mc_8zq296TaI) 这个问题。 使用的数据是库中自带的几个jsno数据

暂时还不支持chatglm3 可以跑下chatglm2就不会有这个报错了

**Comment by nuocheng** [comment]
> > `CUDA_VISIBLE_DEVICES=1 python3 uniform_finetune.py --model_type chatglm --model_name_or_path huggingface.co/THUDM/chatglm3-6b --data ./data/formatted_cot_data/aqua_train.json ./data/formatted_cot_data/ecqa_train.json ./data/formatted_cot_data/esnli_train.json --lora_target_modules query_key_value --lora_r 32 --lora_alpha 32 --lora_dropout 0.1` 运行uniform_finetune.py这个脚本进行进行微调，出现了 ![image](https://private-user-images.githubusercontent.com/31612743/291768541-92227b12-622b-475a-be3f-c0b2b50d5b74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTc1MjMsIm5iZiI6MTcwMzA1NzIyMywicGF0aCI6Ii8zMTYxMjc0My8yOTE3Njg1NDEtOTIyMjdiMTItNjIyYi00NzVhLWJlM2YtYzBiMmI1MGQ1Yjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA3MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNmMwMjE5NzQ3ZTg1OTE5NGJlMzI5NDE2YjFmODE3Y2U2OTEzMDZlOThlZjc5ZGNiZTc4YTg4OWU2YzA1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MaQwpz_lgWNYza4Zn9RiNr1Eiaisa86mc_8zq296TaI) 这个问题。 使用的数据是库中自带的几个jsno数据
> 
> 暂时还不支持chatglm3 可以跑下chatglm2就不会有这个报错了

好的，我试一下2
