### ISSUE TITLE
Missing alpaca-belle-cot-7b?

### ISSUE THREAD

**Issue by ImKeTT** [PhoebusSi/Alpaca-CoT#2]
Incredible work!! Thank you! But it seems that alpaca-belle-cot-7b is missing for now?

**Comment by PhoebusSi** [comment]
Thank you for your attention! We have uploaded `alpaca-belle cot-7b`. We are still iterating and optimizing the model version. Please continue to follow us.

**Comment by ImKeTT** [comment]
great work, thank you!
