### ISSUE TITLE
How to further fine-tune on alpaca

### ISSUE THREAD

**Issue by weberrr** [PhoebusSi/Alpaca-CoT#27]
The code only provides the code for fine-tune on llama and other models. If you want to further fine-tune on alpaca with good fine-tune, how to achieve it

**Comment by weberrr** [comment]
The code only provides the code for fine-tune on llama and other models. If you want to further fine-tune on alpaca with good fine-tune, how to achieve it

**Comment by weberrr** [comment]
the code in 'export_hf_checkpoint.py' is perfect

**Comment by lianzhaoy** [comment]
The export_hf_checkpoint.py file is used to merge the basic model with the lora weight, and then the merged model is fine-tuned based on uniform_finetune.py？

**Comment by lianzhaoy** [comment]
@weberrr Use export_hf_checkpoint.py to merge the basic model and lora weights, and then fine-tune the merged model based on uniform_finetune.py. Is that what it means?
