### ISSUE TITLE
Data from ShareGPT

### ISSUE THREAD

**Issue by xihuai18** [PhoebusSi/Alpaca-CoT#29]
Will crawling the data from ShareGPT (as done by Google Bard and [Vicuna](https://github.com/lm-sys/FastChat)) be possible? The conversations shared by real-person users of ChatGPT are of very high quality.

The repo of ShareGPT: https://github.com/domeccleston/sharegpt.

**Comment by PhoebusSi** [comment]
Many thanks! We will collect the data as soon as possible.
