### ISSUE TITLE
训练效果差，每次回复后面总是要跟一堆重复东西

### ISSUE THREAD

**Issue by yuanluw** [PhoebusSi/Alpaca-CoT#33]
你好，感谢你的开源工作，不过我训练得到的模型效果总是不行，每次输入后面总是跟了一堆重复的东西,,例子如下。但是用你的一系列开源权重模型是没问题的。所以不知道能否给我提供一些训练上的建议，
`
input: hello

response: Hello! 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋 👋

input:你吃饭了吗
response: Yes, I have eaten. 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊 😊
`

一些具体的训练情况如下，选择了llama7b的模型，然后主要是修改了train_batch_size 改成了32(因为觉得训练有点慢就把它加大了)，把梯度累计改成了4，其他没选择的都是代码里的默认参数

`
python3 uniform_finetune.py --model_type llama --model_name_or_path weight/llama-7b-hf \
    --data alpaca --lora_target_modules q_proj v_proj \
    --per_gpu_train_batch_size 32 --learning_rate 3e-4 --epochs 3 --output_dir test_output \
    --gradient_accumulation_steps 4 \
`

测试代码用的app.py，也没有修改里面的内容。

**Comment by yuanluw** [comment]
是的，单卡3090

**Comment by PhoebusSi** [comment]
来加微信细聊：13161685288

**Comment by raihan0824** [comment]
I’m encountering the same problem, can you help me?

**Comment by PhoebusSi** [comment]
Try training on multiple GPUs, or increase the number of `gradient_accumulation_steps`.

**Comment by raihan0824** [comment]
will try. But how about tweaking the parameters? do you know what parameter I should adjust to make the response not repetitive and truthful? I tried changing the temperature to 0.8 and setting the greedy decoding to True

**Comment by raihan0824** [comment]
or should I just train it longer?

**Comment by PhoebusSi** [comment]
1. Raising the temperature has a slight effect on reducing repetition:  higher temperatures have a smoother vocabulary prediction distribution, and a greater chance of picking up words that are not usually picked up. 
2. If you set `greedy` to true, there is no need to configure the temperature.
3. The main reason is that the model is not well trained. More data can be used. If the amount of data is small (50k), it is recommended to train for 3 epoch. If the amount is large (0.5M+), you can only train for 1 epoch.

**Comment by raihan0824** [comment]
my data is 26MB, I guess it's considerably large, right? I trained my data with bloom model

**Comment by raihan0824** [comment]
by 50k do you mean the number of instructions?

**Comment by PhoebusSi** [comment]
yes. 26MB data is fairly large. Is the data quality not good?

**Comment by raihan0824** [comment]
well my data size is 26MB and has 50k instructions. The quality should be similar to the alpaca data, as I only translate it to other language using chatgpt.

**Comment by PhoebusSi** [comment]
I see. This may be due to Bloom's weak ability in your target language. You can collect more data, try larger bloom models, or try the LLM performing well on the target language.

**Comment by raihan0824** [comment]
do you think adding more epochs will solve the problem?

**Comment by PhoebusSi** [comment]
Yes, it should be better.

**Comment by PhoebusSi** [comment]
How many epoches do you set? 3 epochs is suitable for 50k instructions.

**Comment by raihan0824** [comment]
I'll switch the model to llama and see how it goes
