### ISSUE TITLE
fine-tuning完了以后，使用时AutoTokenizer这步报错

### ISSUE THREAD

**Issue by StarRanger** [PhoebusSi/Alpaca-CoT#35]
fine-tuning这部已顺利跑成功了，belle1.5m 的指令集已经替换成我自己的指令集了。
python3 uniform_finetune.py --model_type llama --model_name_or_path decapoda-research/llama-7b-hf \
    --data belle1.5m --lora_target_modules q_proj v_proj \
    --per_gpu_train_batch_size 4 --learning_rate 3e-4 --epochs 1 
 saved_models下面也生成了llama-7b-hf_belle1.5m文件夹，里面有两个文件config.json和pytorch_model.bin 
然后加载模型：
from transformers import AutoTokenizer, AutoModelForCausalLM
import sys
model_path = "./saved_models/llama-7b-hf_belle1.5m" 
model =  AutoModelForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)
运行到tockenizer时，抛异常：
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[5], line 1
----> 1 tokenizer = AutoTokenizer.from_pretrained(model_path)

File ~/.conda/envs/python39/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py:715, in AutoTokenizer.from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    713 else:
    714     if tokenizer_class_py is not None:
--> 715         return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
    716     else:
    717         raise ValueError(
    718             "This tokenizer cannot be instantiated. Please make sure you have `sentencepiece` installed "
    719             "in order to use this tokenizer."
    720         )

File ~/.conda/envs/python39/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1795, in PreTrainedTokenizerBase.from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
   1789     logger.info(
   1790         f"Can't load following files from cache: {unresolved_files} and cannot check if these "
   1791         "files are necessary for the tokenizer to operate."
   1792     )
   1794 if all(full_file_name is None for full_file_name in resolved_vocab_files.values()):
-> 1795     raise EnvironmentError(
   1796         f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you were trying to load it from "
   1797         "'https://huggingface.co/models', make sure you don't have a local directory with the same name. "
   1798         f"Otherwise, make sure '{pretrained_model_name_or_path}' is the correct path to a directory "
   1799         f"containing all relevant files for a {cls.__name__} tokenizer."
   1800     )
   1802 for file_id, file_path in vocab_files.items():
   1803     if file_id not in resolved_vocab_files:

OSError: Can't load tokenizer for '/root/llm/Alpaca-CoT-main/saved_models/llama-7b-hf_belle1.5m'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/root/llm/Alpaca-CoT-main/saved_models/llama-7b-hf_belle1.5m' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

后面该怎么加载啊？还是模型生成时就少点什么？

**Comment by PhoebusSi** [comment]
请用我们的generate.py或app.py来加载模型以测试效果。或者参考这俩脚本中对应的functions来改自己测试脚本。
