### ISSUE TITLE
谁试过pytorch2.0 和pytorch1.X的训练速度的区别

### ISSUE THREAD

**Issue by archwolf118** [PhoebusSi/Alpaca-CoT#38]
我用bloom模型跑的多卡的finetune，但是根据我观察，采用pytorch1.13.1的训练速度和pytorch2.0.0的训练速度，几乎是一样的。想问一下各位大佬，通过lora方法训练模型，pytorch2.0是否有提速？谢谢了。

**Comment by PhoebusSi** [comment]
欢迎来我们的群聊里和大家交流。
