### ISSUE TITLE
llama模型训练中途失败

### ISSUE THREAD

**Issue by zhangyanbo2007** [PhoebusSi/Alpaca-CoT#43]
![WXWorkCapture_16805893188669](https://user-images.githubusercontent.com/9403745/229705327-5c82d2e9-86e8-4881-b16b-fa64255af8b2.png)

**Comment by zhangyanbo2007** [comment]
这个序列长度不是pad补全的吗?，不应该中途训练失败吧

**Comment by PhoebusSi** [comment]
应该是lora这种训练方式带来的特点吧 可以估一下这个变化比例 给出些预留
