### ISSUE TITLE
Have you ever tried fine-tuning ChatGLM?

### ISSUE THREAD

**Issue by terryops** [PhoebusSi/Alpaca-CoT#5]
It's an open-source project from Tsinghua University, offering similar performance to Alpaca from Stanford U, and also emphasizing better ability in Chinese dialogs.

**Comment by PhoebusSi** [comment]
We will soon be integrating ChatGLM into our project.

**Comment by PhoebusSi** [comment]
We have integrated chatGLM.  We will gradually integrate more LLMs.
