### ISSUE TITLE
Issues regarding FastChat dataset

### ISSUE THREAD

**Issue by TranSirius** [PhoebusSi/Alpaca-CoT#56]
The repo marks *FastChat* as subsets from ShareGPT (Show in the table). However, I checked the repo of FastChat and find that their released dataset are processed Alpaca data to demonstrate how to train Vicuna, rather than ShareGPT data they used. You may want to fix this by adding a notice to the description of FastChat.

**Comment by PhoebusSi** [comment]
Thank you for pointing out the error. We will revise it later.
