### ISSUE TITLE
这是一个非常棒的工作，但是cot数据集部分，中文的一些翻译可能是有问题的

### ISSUE THREAD

**Issue by yinfupai** [PhoebusSi/Alpaca-CoT#62]
在cot中文数据集中，不少翻译是有问题的，题目选项中的中文翻译，与最后输出中的答案翻译并不是相同的中文描述，虽然是含义相近，然而这或许会影响中文的训练效果？

**Comment by yhyu13** [comment]
@yinfupai 能举个例子吗？

**Comment by PhoebusSi** [comment]
收到，我们尽快解决这个问题，并更新对应数据。

**Comment by yinfupai** [comment]
> @yinfupai 能举个例子吗？

例如在ecqa_train中第一个

**Comment by PhoebusSi** [comment]
我们尽可能的修正下 但是可能无法cover到所有样本 这个问题在语义理解上影响不大 模型依然可以从中受益并给出reasoning后的结果 但是确实会一定程度上造成复述options能力的下降

**Comment by yinfupai** [comment]
> 我们尽可能的修正下 但是可能无法cover到所有样本 这个问题在语义理解上影响不大 模型依然可以从中受益并给出reasoning后的结果 但是确实会一定程度上造成复述options能力的下降

非常理解，也非常感谢你们的工作。

**Comment by PhoebusSi** [comment]
我们对ecqa数据集进行了重新处理，已更新～
