### ISSUE TITLE
 ThoughtSource annotated dataset for CoT

### ISSUE THREAD

**Issue by yhyu13** [PhoebusSi/Alpaca-CoT#67]
https://github.com/OpenBioLink/ThoughtSource 

ThoughtSource is a meta-dataset and software library for chain-of-thought (CoT) reasoning that integrates multiple datasets to improve future artificial intelligence systems' understanding of CoTs, enable empirical evaluations, and provide training data.

They've release a set of math/science Question/Reasoning/Answer dataset processed in Hugging face dataset format which is pretty cool.

**Comment by KnutJaegersberg** [comment]
very cool

**Comment by dkqkxx** [comment]
thanks, we will consider add this right now.
