### ISSUE TITLE
多轮对话报错

### ISSUE THREAD

**Issue by lin1490188** [PhoebusSi/Alpaca-CoT#73]
NotImplementedError: return_offset_mapping is not available when using Python 
tokenizers. To use this feature, change your tokenizer to one deriving from 
transformers.PreTrainedTokenizerFast. More information on available tokenizers 
at https://github.com/huggingface/transformers/pull/2674

**Comment by PhoebusSi** [comment]
This should be caused by an index mismatch in your local GPU.
