### ISSUE TITLE
运行predict.py报错

### ISSUE THREAD

**Issue by oriCodesPorter** [PhoebusSi/Alpaca-CoT#74]
ValueError: Expected a torch.device with a specified index or an integer, but got:cuda

有人遇到这个问题吗？

**Comment by dkqkxx** [comment]
I'll try to solve this.
Could you provide more details about your python environment?

**Comment by dkqkxx** [comment]
> ValueError: Expected a torch.device with a specified index or an integer, but got:cuda
> 
> 有人遇到这个问题吗？

I pull the newest repo and it works properly in my macheine.
