### ISSUE TITLE
ChatGLM-6B的input问题

### ISSUE THREAD

**Issue by aqtalent** [PhoebusSi/Alpaca-CoT#95]
在generate_and_tokenize_prompt函数中打印返回的tokenized_with_response结果中的input_ids，
为如下形式：
<input_tokens>, <output_tokens>, 130005, 130001, 130004
论文中的输入应该是如下形式：
<input_tokens>, 130001, 130004, <output_tokens>, 130005

下面是打印的tokenized_with_response结果的截图：
<img width="767" alt="image" src="https://user-images.githubusercontent.com/1057439/234532176-17b16fa6-9728-409e-ab55-e7de98e3dff2.png">

**Comment by dkqkxx** [comment]
thanks, repaired.
